'use client';
import {useEffect,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import {supabase} from "../lib/supabase";
const levels=["3ème année collège","Tronc Commun","1ère année Bac","2ème année Bac"];
const tabs=[["home","🏠","Vue d'ensemble"],["students","👨‍🎓","Élèves"],["teachers","👨‍🏫","Professeurs"],["subjects","📚","Matières"],["schedule","🗓️","Emploi du temps"],["qr","📱","QR & Présence"],["payments","💰","Paiements"],["news","📢","Annonces"],["stats","📊","Statistiques"]];
const id=()=>Math.random().toString(36).slice(2);
const load=(k:string)=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}};
export default function Admin(){
 const [tab,setTab]=useState("home"),[ready,setReady]=useState(false);
 const [authReady,setAuthReady]=useState(false),[session,setSession]=useState<any>(null),[isAdmin,setIsAdmin]=useState(false);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[loginError,setLoginError]=useState("");
 useEffect(()=>{let active=true;const check=async(s:any)=>{setSession(s);if(!s){if(active){setIsAdmin(false);setAuthReady(true)};return}const {data}=await supabase.from("admins").select("user_id").eq("user_id",s.user.id).maybeSingle();if(active){setIsAdmin(!!data);setAuthReady(true)}};supabase.auth.getSession().then(({data})=>check(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>check(s));return()=>{active=false;subscription.unsubscribe()}},[]);
 const [students,setStudents]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[schedule,setSchedule]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[news,setNews]=useState<any[]>([]),[presence,setPresence]=useState<any[]>([]),[selected,setSelected]=useState<any>(null);
 const [dbError,setDbError]=useState("");
 const refresh=async()=>{setReady(false);setDbError("");const [a,b,c,d,e,f,g]=await Promise.all([supabase.from("students").select("*").order("created_at",{ascending:false}),supabase.from("teachers").select("*").order("created_at",{ascending:false}),supabase.from("subjects").select("*").order("created_at",{ascending:false}),supabase.from("schedules").select("*").order("created_at",{ascending:false}),supabase.from("payments").select("*").order("created_at",{ascending:false}),supabase.from("announcements").select("*").order("created_at",{ascending:false}),supabase.from("attendance").select("*").order("attended_on",{ascending:false})]);const bad=[a,b,c,d,e,f,g].find((x:any)=>x.error);if(bad)setDbError((bad as any).error.message);else{setStudents(a.data||[]);setTeachers(b.data||[]);setSubjects(c.data||[]);setSchedule(d.data||[]);setPayments(e.data||[]);setNews(f.data||[]);setPresence(g.data||[])}setReady(true)};
 useEffect(()=>{if(session&&isAdmin)refresh()},[session,isAdmin]);
 const del=async(set:any,arr:any[],x:string,table:string)=>{const {error}=await supabase.from(table).delete().eq("id",x);if(error)setDbError(error.message);else await refresh()};
 const add=async(e:any,set:any,arr:any[],type:string)=>{e.preventDefault();setDbError("");let f=new FormData(e.currentTarget),o:any={};f.forEach((v,k)=>{if(v!=="")o[k]=v});let table="";if(type==="student"){table="students";o={full_name:o.name,phone:o.phone||null,email:o.email||null,level:o.level}}if(type==="teacher"){table="teachers";o={full_name:o.name,phone:o.phone||null,email:o.email||null}}if(type==="subject"){table="subjects";o={name:o.name,level:o.level,teacher_id:o.teacher_id||null}}if(type==="schedule"){table="schedules";o={level:o.level,subject_id:o.subject_id||null,teacher_id:o.teacher_id||null,day:o.day,start_time:o.start_time||null,end_time:o.end_time||null,room:o.room||null}}if(type==="payment"){table="payments";o={student_id:o.student_id,amount:Number(o.amount),status:o.status||"Payé",note:o.note||null}}if(type==="news"){table="announcements";o={title:o.title,content:o.content,is_published:true}}const inserted=type==="student"?await supabase.from(table).insert(o).select().single():await supabase.from(table).insert(o);if(inserted.error){setDbError(inserted.error.message);return}if(type==="student"&&o.email&&inserted.data?.qr_code){const r=await fetch("/api/send-qr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:o.email,name:o.full_name,qrCode:inserted.data.qr_code})});if(!r.ok){const x=await r.json().catch(()=>({}));setDbError("Élève ajouté, mais email non envoyé: "+(x.error||"erreur d'envoi"));return}}e.currentTarget.reset();await refresh()};
 const mark=async(status:string)=>{if(!selected)return;let attended_on=new Date().toISOString().slice(0,10);const {error}=await supabase.from("attendance").upsert({student_id:selected.id,attended_on,status},{onConflict:"student_id,attended_on"});if(error)setDbError(error.message);else await refresh()};
 if(!authReady)return <div className="loading">Chargement...</div>;
 if(!session)return <main className="loginPage"><form className="loginBox" onSubmit={async(e)=>{e.preventDefault();setLoginError("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setLoginError("Email ou mot de passe incorrect.")}}><img src="/logo.svg" alt="Centre Les Profs"/><h1>Administration</h1><p>Connecte-toi pour accéder au dashboard.</p>{loginError&&<div className="error">{loginError}</div>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Mot de passe" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="submit">Se connecter</button></form></main>;
 if(!isAdmin)return <main className="loginPage"><div className="loginBox"><h1>Accès refusé</h1><p>Ce compte n'a pas les droits administrateur.</p><button onClick={()=>supabase.auth.signOut()}>Se déconnecter</button></div></main>;
 if(!ready)return <div className="loading">Chargement de Supabase...</div>;
 const today=new Date().toISOString().slice(0,10), present=presence.filter((p:any)=>p.attended_on===today&&p.status==="Présent").length;
 const Form=({children,onSubmit}:any)=><form className="form" onSubmit={onSubmit}>{children}</form>;
 return <main className="dash"><aside><a className="logo" href="/"><img src="/logo.svg"/><span>Centre<br/><b>Les Profs</b></span></a>{tabs.map(t=><button className={tab===t[0]?"active":""} onClick={()=>setTab(t[0])} key={t[0]}><i>{t[1]}</i><span>{t[2]}</span></button>)}<a className="public" href="/">↗ Site public</a><button className="logout" onClick={()=>supabase.auth.signOut()}>🚪 Déconnexion</button></aside>
 <section className="content"><div className="top"><div><p className="tag">ADMINISTRATION</p><h1>{tabs.find(x=>x[0]===tab)?.[2]}</h1></div><b>🔴 Admin</b></div>
 {dbError&&<div className="error" style={{marginBottom:16}}>{dbError}</div>}
 {tab==="home"&&<><div className="metrics"><Metric i="👨‍🎓" n={students.length} t="Élèves"/><Metric i="👨‍🏫" n={teachers.length} t="Professeurs"/><Metric i="📚" n={subjects.length} t="Matières"/><Metric i="✅" n={present} t="Présents aujourd'hui"/></div><Box title="Bienvenue"><p>Gère ton centre depuis un seul endroit. Commence par ajouter les élèves, les professeurs et les matières.</p></Box></>}
 {tab==="students"&&<div className="cols"><Box title="Ajouter un élève"><Form onSubmit={(e:any)=>add(e,setStudents,students,"student")}><input name="name" placeholder="Nom complet" required/><input name="email" type="email" placeholder="Email du tuteur / élève" required/><input name="phone" placeholder="Téléphone"/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter & envoyer le QR 📧</button></Form></Box><Box title={"Liste des élèves ("+students.length+")"}>{students.map(s=><Row key={s.id} title={s.full_name} sub={s.level+" • "+(s.phone||"")+(s.email?" • "+s.email:"")} action={()=>del(setStudents,students,s.id,"students")}/>)}{!students.length&&<p className="empty">Aucun élève.</p>}</Box></div>}
 {tab==="teachers"&&<div className="cols"><Box title="Ajouter un professeur"><Form onSubmit={(e:any)=>add(e,setTeachers,teachers,"teacher")}><input name="name" placeholder="Nom complet" required/><input name="subject" placeholder="Matière"/><input name="phone" placeholder="Téléphone"/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter</button></Form></Box><Box title="Professeurs">{teachers.map(x=><Row key={x.id} title={x.name} sub={(x.subject||"")+" • "+x.level} action={()=>del(setTeachers,teachers,x.id,"teachers")}/>)}{!teachers.length&&<p className="empty">Aucun professeur.</p>}</Box></div>}
 {tab==="subjects"&&<div className="cols"><Box title="Ajouter une matière"><Form onSubmit={(e:any)=>add(e,setSubjects,subjects,"subject")}><input name="name" placeholder="Nom de la matière" required/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter</button></Form></Box><Box title="Matières">{subjects.map(x=><Row key={x.id} title={x.name} sub={x.level} action={()=>del(setSubjects,subjects,x.id,"subjects")}/>)}{!subjects.length&&<p className="empty">Aucune matière.</p>}</Box></div>}
 {tab==="schedule"&&<div className="cols"><Box title="Nouvelle séance"><Form onSubmit={(e:any)=>add(e,setSchedule,schedule,"schedule")}><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><input name="subject" placeholder="Matière" required/><input name="teacher" placeholder="Professeur"/><input name="day" placeholder="Jour"/><input name="time" placeholder="Heure"/><button>Ajouter</button></Form></Box><Box title="Emploi du temps">{schedule.map(x=><Row key={x.id} title={x.subject+" — "+x.level} sub={(x.day||"")+" • "+(x.time||"")+" • "+(x.teacher||"")} action={()=>del(setSchedule,schedule,x.id,"schedules")}/>)}{!schedule.length&&<p className="empty">Aucune séance.</p>}</Box></div>}
 {tab==="qr"&&<><div style={{marginBottom:16}}><a href="/admin/scan"><button>📷 Ouvrir le scanner QR</button></a></div><div className="cols"><Box title="Choisir un élève"><div className="selectList">{students.map(s=><button className="pick" onClick={()=>setSelected(s)} key={s.id}>{s.full_name}<small>{s.qr_code}</small></button>)}</div>{!students.length&&<p className="empty">Ajoute des élèves d'abord.</p>}</Box><Box title={selected?selected.full_name:"QR Code & présence"}>{selected?<div className="qr"><QRCodeSVG value={selected.qr_code} size={210}/><code>{selected.qr_code}</code><div><button onClick={()=>mark("Présent")} className="green">✓ Présent</button><button onClick={()=>mark("Absent")} className="redbtn">✕ Absent</button><button onClick={()=>mark("Retard")} className="orange">⏱ Retard</button></div></div>:<p className="empty">Sélectionne un élève.</p>}</Box></div></>}
 {tab==="payments"&&<div className="cols"><Box title="Ajouter un paiement"><Form onSubmit={(e:any)=>add(e,setPayments,payments,"payment")}><select name="student"><option>Choisir un élève</option>{students.map(s=><option key={s.id}>{s.full_name}</option>)}</select><input name="amount" type="number" placeholder="Montant DH" required/><select name="status"><option>Payé</option><option>En attente</option></select><button>Enregistrer</button></Form></Box><Box title="Paiements">{payments.map(x=><Row key={x.id} title={x.student} sub={x.amount+" DH • "+x.status} action={()=>del(setPayments,payments,x.id,"payments")}/>)}{!payments.length&&<p className="empty">Aucun paiement.</p>}</Box></div>}
 {tab==="news"&&<div className="cols"><Box title="Nouvelle annonce"><Form onSubmit={(e:any)=>add(e,setNews,news,"news")}><input name="title" placeholder="Titre" required/><textarea name="text" placeholder="Contenu" required/><button>Publier</button></Form></Box><Box title="Annonces">{news.map(x=><Row key={x.id} title={"📢 "+x.title} sub={x.text} action={()=>del(setNews,news,x.id,"announcements")}/>)}{!news.length&&<p className="empty">Aucune annonce.</p>}</Box></div>}
 {tab==="stats"&&<><div className="metrics"><Metric i="👨‍🎓" n={students.length} t="Total élèves"/><Metric i="👨‍🏫" n={teachers.length} t="Total professeurs"/><Metric i="💰" n={payments.filter(x=>x.status==="Payé").length} t="Paiements payés"/><Metric i="🗓️" n={schedule.length} t="Séances"/></div><Box title="Répartition par niveau">{levels.map(x=><div className="stat" key={x}><span>{x}</span><b>{students.filter(s=>s.level===x).length} élèves</b></div>)}</Box></>}
 </section></main>}
function Box({title,children}:{title:string,children:any}){return <div className="box"><h2>{title}</h2>{children}</div>}
function Metric({i,n,t}:{i:string,n:number,t:string}){return <div className="metric"><i>{i}</i><div><b>{n}</b><small>{t}</small></div></div>}
function Row({title,sub,action}:{title:string,sub:string,action:()=>void}){return <div className="row"><div><b>{title}</b><small>{sub}</small></div><button className="delete" onClick={action}>Supprimer</button></div>}
