'use client';
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {QRCodeSVG} from "qrcode.react";
import {supabase} from "../../lib/supabase";
export default function StudentPage(){
 const params=useParams(); const router=useRouter(); const code=decodeURIComponent(String(params.code||"")).toUpperCase();
 const [student,setStudent]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!code)return;(async()=>{const {data,error}=await supabase.rpc("get_student_portal",{p_code:code});if(error||!data?.length)setError("Code élève introuvable.");else setStudent(data[0]);setLoading(false)})()},[code]);
 if(loading)return <main><section><h2>Chargement...</h2></section></main>;
 if(error)return <main><section><h2>{error}</h2><button onClick={()=>router.push("/")}>Retour</button></section></main>;
 const qrSvg=()=>{const svg=document.getElementById("student-qr");if(!svg)return;const clone=svg.cloneNode(true) as SVGElement;clone.setAttribute("width","900");clone.setAttribute("height","900");const xml=new XMLSerializer().serializeToString(clone);const blob=new Blob([xml],{type:"image/svg+xml"});const url=URL.createObjectURL(blob);const img=new Image();img.onload=()=>{const canvas=document.createElement("canvas");canvas.width=900;canvas.height=900;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.fillStyle="white";ctx.fillRect(0,0,900,900);ctx.drawImage(img,0,0,900,900);URL.revokeObjectURL(url);canvas.toBlob((png)=>{if(!png)return;const pngUrl=URL.createObjectURL(png);const a=document.createElement("a");a.href=pngUrl;a.download="QR-"+student.qr_code+".png";a.click();setTimeout(()=>URL.revokeObjectURL(pngUrl),1000)},"image/png")};img.src=url};
 return <main><header><a className="brand" href="/"><img src="/logo.png" alt="Centre Les Profs"/><b>CENTRE LES PROFS</b></a><nav><button onClick={()=>router.push("/")}>Déconnexion</button></nav></header><section><p className="tag">MON ESPACE PERSONNEL</p><h1>Bienvenue, {student.full_name} 👋</h1><div className="cards"><article><b>🎓</b><h3>Mon profil</h3><p><b>Code :</b> {student.qr_code}</p><p><b>Niveau :</b> {student.level||"-"}</p><p><b>Téléphone :</b> {student.phone||"-"}</p><p><b>Email :</b> {student.email||"-"}</p></article><article><b>📱</b><h3>Mon QR Code</h3><div style={{background:"white",padding:12,borderRadius:12,display:"inline-block"}}><QRCodeSVG id="student-qr" value={student.qr_code} size={220}/></div><p><button onClick={qrSvg}>⬇️ Télécharger mon QR Code</button></p></article></div><div className="cards"><article><b>📚</b><h3>Mes matières</h3>{(student.subjects||[]).length?(student.subjects||[]).map((x:any,i:number)=><p key={i}>{x.name}</p>):<p>Aucune matière enregistrée.</p>}</article><article><b>📅</b><h3>Ma présence</h3><p>Présent : {(student.attendance||[]).filter((x:any)=>x.status==="Présent").length}</p><p>Absent : {(student.attendance||[]).filter((x:any)=>x.status==="Absent").length}</p></article><article><b>💰</b><h3>Mes paiements</h3>{(student.payments||[]).length?(student.payments||[]).map((x:any,i:number)=><p key={i}>{x.amount} DH — {x.status}</p>):<p>Aucun paiement enregistré.</p>}</article></div></section></main>
}