'use client';
import {useEffect,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import {supabase} from "./lib/supabase";
const levels=["3ème année collège","Tronc Commun","1ère année Bac","2ème année Bac"];
export default function Home(){
const [subjects,setSubjects]=useState<any[]>([]),[schedules,setSchedules]=useState<any[]>([]),[news,setNews]=useState<any[]>([]);
const [code,setCode]=useState(""),[student,setStudent]=useState<any>(null),[portalError,setPortalError]=useState(""),[searching,setSearching]=useState(false);
useEffect(()=>{(async()=>{const a=await supabase.from("subjects").select("name,level,teachers(full_name)").order("name");const b=await supabase.from("schedules").select("day,start_time,end_time,room,level,subjects(name),teachers(full_name)").order("created_at");const c=await supabase.from("announcements").select("title,content,created_at").eq("is_published",true).order("created_at",{ascending:false}).limit(6);setSubjects(a.data||[]);setSchedules(b.data||[]);setNews(c.data||[])})()},[]);
const openPortal=async(e:any)=>{e.preventDefault();setPortalError("");setStudent(null);setSearching(true);const {data,error}=await supabase.rpc("get_student_portal",{p_code:code.trim().toUpperCase()});setSearching(false);if(error){setPortalError("Erreur lors de la recherche.");return}if(!data?.length){setPortalError("Code introuvable.");return}setStudent(data[0])};
return <main><header><a className="brand" href="/"><img src="/logo.svg" alt="Centre Les Profs"/><b>CENTRE LES PROFS</b></a><nav><a href="#levels">Niveaux</a><a href="#subjects">Matières</a><a href="#schedule">Emploi du temps</a><a href="#news">Annonces</a><a className="red" href="/admin">Administration</a></nav></header>
<section className="hero"><div><p className="tag">CENTRE DE SOUTIEN SCOLAIRE</p><h1>Construisons ensemble <span>la réussite.</span></h1><p>Une plateforme moderne pour accompagner les élèves.</p></div><div className="heroIcon">🎓</div></section>
<section id="student"><p className="tag">ESPACE ÉLÈVE</p><h2>Consulter mes informations</h2><div className="box" style={{maxWidth:700,margin:"20px auto"}}><form className="form" onSubmit={openPortal}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Exemple : CLP-4085E2F6B4" required/><button>{searching?"Recherche...":"Accéder à mon espace"}</button></form>{portalError&&<p className="error">{portalError}</p>}
{student&&<div style={{marginTop:20}}><h2>👋 Bonjour {student.full_name}</h2><p><b>Code élève :</b> {student.qr_code}</p><p><b>Niveau :</b> {student.level}</p><p><b>Téléphone :</b> {student.phone||"-"}</p><p><b>Email :</b> {student.email||"-"}</p><h3>📱 Mon QR Code</h3><div style={{background:"white",display:"inline-block",padding:12,borderRadius:12}}><QRCodeSVG value={student.qr_code} size={220}/></div><h3>📚 Matières</h3><ul>{(student.subjects||[]).map((x:any,i:number)=><li key={i}>{x.name} — {x.level}</li>)}</ul><h3>📅 Présence</h3><p>Présent : {(student.attendance||[]).filter((x:any)=>x.status==="Présent").length} • Absent : {(student.attendance||[]).filter((x:any)=>x.status==="Absent").length}</p><h3>💰 Paiements</h3>{(student.payments||[]).length?(student.payments||[]).map((x:any,i:number)=><p key={i}>{x.amount} DH — {x.status} {x.valid_until?("• Valide jusqu'au "+x.valid_until):""}</p>):<p>Aucun paiement enregistré.</p>}</div>}</div></section>
<section id="levels"><p className="tag">NOS NIVEAUX</p><h2>Un accompagnement pour chaque étape</h2><div className="cards">{levels.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{subjects.filter(s=>s.level===x).map(s=>s.name).join(" • ")||"Matières bientôt disponibles."}</p></article>)}</div></section><section id="subjects"><p className="tag">NOS MATIÈRES</p><h2>Matières et professeurs</h2><div className="cards">{subjects.map((s,i)=><article key={i}><b>📚</b><h3>{s.name}</h3><p>{s.level} • {s.teachers?.full_name||"Professeur à définir"}</p></article>)}</div></section><section id="schedule" className="dark"><p className="tag">EMPLOI DU TEMPS</p><h2>Les séances du centre</h2><div className="publicList">{schedules.map((s,i)=><article key={i}><b>{s.subjects?.name||"Séance"}</b><span>{s.level} • {s.day} • {s.start_time?.slice(0,5)||""}-{s.end_time?.slice(0,5)||""} • {s.room||"Salle"}</span></article>)}</div></section><section id="news"><p className="tag">ACTUALITÉS</p><h2>Annonces du centre</h2><div className="cards">{news.map((n,i)=><article key={i}><b>📢</b><h3>{n.title}</h3><p>{n.content}</p></article>)}</div></section><footer>© {new Date().getFullYear()} Centre Les Profs</footer></main>
}