'use client';
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabase} from "./lib/supabase";
const levels=["3ème année collège","Tronc Commun","1ère année Bac","2ème année Bac"];
function StudentLogin(){
 const [code,setCode]=useState(""); const router=useRouter();
 const go=(e:any)=>{e.preventDefault(); const c=code.trim().toUpperCase(); if(c) router.push("/eleve/"+encodeURIComponent(c));};
 return <section><p className="tag">ESPACE ÉLÈVE</p><h2>Accéder à mon espace personnel</h2><div className="box" style={{maxWidth:700,margin:"20px auto"}}><form className="form" onSubmit={go}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Exemple : CLP-4085E2F6B4" required/><button>Accéder à mon espace</button></form></div></section>
}
export default function Home(){const [subjects,setSubjects]=useState<any[]>([]),[schedules,setSchedules]=useState<any[]>([]),[news,setNews]=useState<any[]>([]);useEffect(()=>{(async()=>{const a=await supabase.from("subjects").select("name,level,teachers(full_name)").order("name");const b=await supabase.from("schedules").select("day,start_time,end_time,room,level,subjects(name),teachers(full_name)").order("created_at");const c=await supabase.from("announcements").select("title,content,created_at").eq("is_published",true).order("created_at",{ascending:false}).limit(6);setSubjects(a.data||[]);setSchedules(b.data||[]);setNews(c.data||[])})()},[]);return <main><header><a className="brand" href="/"><img src="/logo.svg" alt="Centre Les Profs"/><b>CENTRE LES PROFS</b></a><nav><a href="#levels">Niveaux</a><a href="#subjects">Matières</a><a href="#schedule">Emploi du temps</a><a href="#news">Annonces</a><a className="red" href="/admin">Administration</a></nav></header><section className="hero"><div><p className="tag">CENTRE DE SOUTIEN SCOLAIRE</p><h1>Construisons ensemble <span>la réussite.</span></h1><p>Une plateforme moderne pour accompagner les élèves.</p></div><div className="heroIcon">🎓</div></section><StudentLogin/><section id="levels"><p className="tag">NOS NIVEAUX</p><h2>Un accompagnement pour chaque étape</h2><div className="cards">{levels.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{subjects.filter(s=>s.level===x).map(s=>s.name).join(" • ")||"Matières bientôt disponibles."}</p></article>)}</div></section><section id="subjects"><p className="tag">NOS MATIÈRES</p><h2>Matières et professeurs</h2><div className="cards">{subjects.map((s,i)=><article key={i}><b>📚</b><h3>{s.name}</h3><p>{s.level} • {s.teachers?.full_name||"Professeur à définir"}</p></article>)}</div></section><section id="schedule" className="dark"><p className="tag">EMPLOI DU TEMPS</p><h2>Les séances du centre</h2><div className="publicList">{schedules.map((s,i)=><article key={i}><b>{s.subjects?.name||"Séance"}</b><span>{s.level} • {s.day} • {s.start_time?.slice(0,5)||""}-{s.end_time?.slice(0,5)||""} • {s.room||"Salle"}</span></article>)}</div></section><section id="news"><p className="tag">ACTUALITÉS</p><h2>Annonces du centre</h2><div className="cards">{news.map((n,i)=><article key={i}><b>📢</b><h3>{n.title}</h3><p>{n.content}</p></article>)}</div></section><footer>© {new Date().getFullYear()} Centre Les Profs</footer></main>}